# Default values for xavier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: zaqar
env: production
maxReplicas: 10
cpuUsage: 80

image:
  name: zaqar
  tag: ''
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  portName: http

environment: 
  SENDGRID_APIKEY:
  DEFAULT_FROM_ADDRESS:
  DEFAULT_FROM_NAME:
  AUTH_USERNAME:
  AUTH_PASSWORD:

resources:
  requests:
    cpu: 250m
