# This is a basic workflow to help you get started with Actions

name: Test coverage

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        node: ['12', '14', '16']
    name: Node ${{ matrix.node }} test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm i -g mocha nyc typescript && npm i
        name: Install packages

      - run: npm run build:clean
        name: Build project

      - name: Test and coverage
        run: npm run coverage
